"""Platform / LLMOps / infra / FinOps / security flashcards (authoritative + repo-grounded)."""

from __future__ import annotations

from study.models import FlashCard, SourceRef


def _s(title: str, url: str = "", kind: str = "docs") -> SourceRef:
    return SourceRef(title=title, url=url, kind=kind)  # type: ignore[arg-type]


def platform_flashcards() -> list[FlashCard]:
    return [
        # LLMOps
        FlashCard(
            id="fc-llmops-map",
            front="LLMOps discipline map (this app)",
            track="llmops",
            tags=["llmops", "as-built"],
            kind="process",
            what="Operating model for LLM features: registry, prompts, guardrails, evals, budgets, obs, CI.",
            how="Keep GraphRAG core deterministic; optional LLM via gateway; enforce outside the model.",
            where="docs/sdd/09-PLATFORM-LLMOPS.md + packages guardrails/, evals/, gateway/, finops/, observability/.",
            when="Any time LLM wording or tools are considered for production.",
            who="Platform + app engineers; ADR 0001.",
            why="Auditability and cost control for warranty answers.",
            say_aloud="GraphRAG primary; LLM optional; gates outside the model.",
            sources=[
                _s("Project SDD 09-PLATFORM-LLMOPS", "", "docs"),
                _s(
                    "Google — Practitioners guide to MLOps",
                    "https://cloud.google.com/resources/mlops-whitepaper",
                    "docs",
                ),
            ],
            related_module_ids=["10-llmops-disciplines"],
        ),
        FlashCard(
            id="fc-llm-enabled",
            front="llm_enabled flag",
            track="llmops",
            tags=["config", "gateway"],
            kind="concept",
            what="Feature flag that turns on the LLM gateway path.",
            how="settings.llm_enabled default false; when true, gateway routes with registry aliases.",
            where="config/settings.py, gateway/",
            when="Only when product wants LLM rewrite/help — not required for GraphRAG diagnose.",
            who="Operators via env/config.",
            why="Default-off protects cost and determinism.",
            sources=[_s("Project config/settings.py", "", "docs")],
            related_module_ids=["10-llmops-disciplines"],
            difficulty="easy",
        ),
        FlashCard(
            id="fc-model-registry",
            front="Model registry pin",
            track="llmops",
            tags=["modelops", "registry"],
            kind="pattern",
            what="Alias → pinned provider model id mapping in git.",
            how="Edit models/registry.yaml deliberately; re-eval after bumps.",
            where="models/registry.yaml",
            when="Changing models or adding aliases.",
            who="ModelOps owner.",
            why="Unpinned 'latest' models silently change behavior.",
            sources=[
                _s("MLflow Model Registry concepts", "https://mlflow.org/docs/latest/model-registry.html", "docs"),
            ],
            related_module_ids=["10-llmops-disciplines", "20-synthetic-mlops-images"],
        ),
        FlashCard(
            id="fc-promptops",
            front="PromptOps",
            track="llmops",
            tags=["prompts", "versioning"],
            kind="concept",
            what="Treat prompts as versioned artifacts with owners and changelogs.",
            how="prompts/diagnosis-rewriter/v1.yaml + CHANGELOG; schema in prompts/_schema.json.",
            where="prompts/, promptops/",
            when="Any LLM wording path enabled.",
            who="Prompt owners.",
            why="Prompt drift is a production regression class.",
            sources=[_s("Project prompts/", "", "docs")],
            related_module_ids=["10-llmops-disciplines"],
        ),
        # Observability
        FlashCard(
            id="fc-three-pillars",
            front="Observability three pillars",
            track="observability",
            tags=["logs", "metrics", "traces"],
            kind="theory",
            what="Logs (events), metrics (aggregates), traces (request paths).",
            how="JSON logs + request_id; Prometheus /metrics; OTEL traces when enabled.",
            where="observability/*, monitoring/*, docker-compose.observability.yaml",
            when="Always for API health; OTEL opt-in for deep latency debug.",
            who="SRE / platform.",
            why="Cannot operate what you cannot measure.",
            sources=[
                _s("OpenTelemetry docs", "https://opentelemetry.io/docs/", "docs"),
                _s(
                    "Google SRE Book — monitoring",
                    "https://sre.google/sre-book/monitoring-distributed-systems/",
                    "docs",
                ),
            ],
            related_module_ids=["11-observability-monitoring"],
        ),
        FlashCard(
            id="fc-prometheus",
            front="Prometheus scrape model",
            track="observability",
            tags=["prometheus", "metrics"],
            kind="concept",
            what="Pull-based metrics collector that scrapes HTTP /metrics endpoints.",
            how="prometheus.yml lists jobs/targets; rules evaluate alerts.",
            where="monitoring/prometheus/prometheus.yml + rules/",
            when="Continuous in staging/prod monitoring stacks.",
            who="Observability owners.",
            why="Standard cloud-native metrics backbone.",
            sources=[_s("Prometheus docs", "https://prometheus.io/docs/introduction/overview/", "docs")],
            related_module_ids=["11-observability-monitoring"],
        ),
        FlashCard(
            id="fc-sli-slo",
            front="SLI / SLO / error budget",
            track="observability",
            tags=["sre", "slo"],
            kind="theory",
            what="SLI measures user-visible reliability; SLO is target; error budget is allowed unreliability.",
            how="Define diagnose latency/error SLIs; alert on burn; use for canary analysis.",
            where="monitoring rules + progressive delivery analysis.",
            when="Production reliability management.",
            who="SRE + product.",
            why="Turns 'is it up?' into objective policy.",
            sources=[
                _s(
                    "Google SRE Book — Service Level Objectives",
                    "https://sre.google/sre-book/service-level-objectives/",
                    "docs",
                ),
            ],
            related_module_ids=["11-observability-monitoring", "15-k8s-helm-rollouts"],
        ),
        # Evals
        FlashCard(
            id="fc-eval-smoke",
            front="Eval smoke suite",
            track="evals",
            tags=["evals", "ci"],
            kind="process",
            what="Fast quality/safety check run on every PR.",
            how="python evals/run_eval.py --suite smoke in ci.yml",
            where="evals/ + .github/workflows/ci.yml",
            when="Every PR/push to main or feature/**",
            who="CI.",
            why="Catch ranking/safety regressions before merge.",
            sources=[_s("Project evals/README.md", "", "docs")],
            related_module_ids=["12-evalops-gates"],
            difficulty="easy",
        ),
        FlashCard(
            id="fc-eval-thresholds",
            front="Eval thresholds (floors)",
            track="evals",
            tags=["evals", "quality"],
            kind="pattern",
            what="Minimum metric values required to pass a gate.",
            how="Configured in evals/thresholds.yaml; CI fails if below.",
            where="evals/thresholds.yaml",
            when="Every gated eval run.",
            who="Quality owners.",
            why="Without floors, evals are dashboards not gates.",
            pitfalls=["Lowering floors to go green"],
            say_aloud="Never lower thresholds to silence a red build — fix the regression.",
            sources=[_s("Project docs/sdd/09-PLATFORM-LLMOPS.md", "", "docs")],
            related_module_ids=["12-evalops-gates"],
        ),
        FlashCard(
            id="fc-safety-eval",
            front="Safety eval suite",
            track="evals",
            tags=["security", "evals", "injection"],
            kind="process",
            what="Adversarial cases (injection/jailbreak style) that must pass 100% in smoke.",
            how="evals/safety/injection.jsonl exercised by run_eval.",
            where="evals/safety/",
            when="Every smoke run.",
            who="Security + quality.",
            why="Guardrails need regression tests, not vibes.",
            sources=[
                _s(
                    "OWASP LLM Top 10",
                    "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
                    "standard",
                ),
            ],
            related_module_ids=["12-evalops-gates", "18-security-guardrails"],
        ),
        # CI/CD
        FlashCard(
            id="fc-gha-ci",
            front="GitHub Actions CI workflow",
            track="cicd",
            tags=["github-actions", "ci"],
            kind="process",
            what="Automated checks on push/PR.",
            how=".github/workflows/ci.yml — secrets, ruff, pytest, eval smoke, frontend, images.",
            where=".github/workflows/",
            when="Every PR to main/feature/**",
            who="All contributors via CI.",
            why="Integrate continuously with evidence.",
            sources=[_s("GitHub Actions docs", "https://docs.github.com/en/actions", "docs")],
            related_module_ids=["13-cicd-github-actions"],
        ),
        FlashCard(
            id="fc-supply-chain",
            front="Software supply chain controls",
            track="cicd",
            tags=["sbom", "trivy", "signing"],
            kind="pattern",
            what="Prove what you built and that artifacts are safe to run.",
            how="Secret scan, dep audit, image scan, SBOM, sign/verify policy (as configured).",
            where="ci.yml, deploy/policy/verify-images.yaml",
            when="Building and deploying container images.",
            who="Platform security.",
            why="Compromised deps/images are production incidents.",
            sources=[
                _s("SLSA framework", "https://slsa.dev/", "standard"),
                _s("Sigstore / cosign", "https://docs.sigstore.dev/", "docs"),
            ],
            related_module_ids=["13-cicd-github-actions"],
        ),
        FlashCard(
            id="fc-cd-eval-gate",
            front="CD eval-gate before deploy",
            track="cicd",
            tags=["cd", "evals"],
            kind="process",
            what="Deployment pipeline step that fails if quality floors fail.",
            how="cd.yml runs eval-gate then deploy strategy (including optional canary).",
            where=".github/workflows/cd.yml",
            when="Release/deploy.",
            who="Release automation.",
            why="Don't ship silent quality regressions.",
            sources=[_s("Project cd.yml", "", "docs")],
            related_module_ids=["13-cicd-github-actions", "12-evalops-gates"],
        ),
        # Docker
        FlashCard(
            id="fc-dockerfile",
            front="Dockerfile",
            track="infra",
            tags=["docker", "containers"],
            kind="concept",
            what="Recipe to build a container image.",
            how="FROM base, COPY, RUN, ENTRYPOINT; prefer multi-stage for slim runtime.",
            where="docker/Dockerfile.api|frontend|etl|mock",
            when="Packaging services for CI and deploy.",
            who="App/platform engineers.",
            why="Reproducible runtime.",
            sources=[_s("Docker docs — Dockerfile", "https://docs.docker.com/reference/dockerfile/", "docs")],
            related_module_ids=["14-docker-compose"],
            difficulty="easy",
        ),
        FlashCard(
            id="fc-compose-dual-neo4j",
            front="Compose dual Neo4j",
            track="infra",
            tags=["docker", "neo4j"],
            kind="pattern",
            what="Two Neo4j services for staging and production locally.",
            how="docker-compose.infra.yaml maps 7687 prod and 7688 staging.",
            where="docker/docker-compose.infra.yaml",
            when="Local dual-graph demos and promote tests.",
            who="Developers.",
            why="Matches promote safety model.",
            sources=[_s("Docker Compose docs", "https://docs.docker.com/compose/", "docs")],
            related_module_ids=["14-docker-compose", "03-etl-pipeline"],
        ),
        # K8s / Helm
        FlashCard(
            id="fc-k8s-deployment",
            front="Kubernetes Deployment",
            track="infra",
            tags=["kubernetes"],
            kind="concept",
            what="Controller maintaining desired Pod replicas and rolling updates.",
            how="Declare template + replicas; kubectl apply / GitOps.",
            where="k8s/base/*-deployment.yaml",
            when="Running API on a cluster.",
            who="Platform engineers.",
            why="Self-heal and roll out versions safely.",
            sources=[
                _s(
                    "Kubernetes Deployments",
                    "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/",
                    "docs",
                )
            ],
            related_module_ids=["15-k8s-helm-rollouts"],
        ),
        FlashCard(
            id="fc-helm-chart",
            front="Helm chart",
            track="infra",
            tags=["helm", "kubernetes"],
            kind="concept",
            what="Versioned package of Kubernetes templates + default values.",
            how="helm install/upgrade with -f values-ENV.yaml; templates render manifests.",
            where="Interview skill; repo uses overlays/rollouts more than full charts.",
            when="Packaging repeatable installs across envs.",
            who="Platform engineers.",
            why="Parameterize without copy-paste YAML sprawl.",
            sources=[_s("Helm docs", "https://helm.sh/docs/", "docs")],
            related_module_ids=["15-k8s-helm-rollouts"],
        ),
        FlashCard(
            id="fc-canary",
            front="Canary release",
            track="infra",
            tags=["progressive-delivery", "canary"],
            kind="pattern",
            what="Send a small % of traffic to new version; analyze; promote or rollback.",
            how="Argo Rollouts / Flagger with metrics analysis; pair with eval quality.",
            where="deploy/rollouts/",
            when="Risky changes (model alias, ranking, API).",
            who="Release engineering.",
            why="Limit blast radius.",
            sources=[
                _s("Argo Rollouts docs", "https://argo-rollouts.readthedocs.io/", "docs"),
                _s("Flagger docs", "https://docs.flagger.app/", "docs"),
            ],
            related_module_ids=["15-k8s-helm-rollouts", "13-cicd-github-actions"],
        ),
        # Terraform
        FlashCard(
            id="fc-terraform-plan",
            front="terraform plan / apply",
            track="infra",
            tags=["terraform", "iac"],
            kind="command",
            what="Plan previews resource diffs; apply executes them.",
            how="terraform init && plan -out && apply (reviewed).",
            where="infra/terraform/ (scaffold in this repo).",
            when="Provisioning cloud resources.",
            who="Infra engineers.",
            why="No surprise cloud changes.",
            code="terraform init\nterraform plan -out tf.plan\nterraform apply tf.plan",
            language="bash",
            sources=[_s("Terraform docs", "https://developer.hashicorp.com/terraform/docs", "docs")],
            related_module_ids=["16-iac-terraform"],
        ),
        FlashCard(
            id="fc-tf-state",
            front="Terraform state",
            track="infra",
            tags=["terraform", "state"],
            kind="concept",
            what="Mapping between config addresses and real cloud object IDs.",
            how="Remote backend + locking for teams; never hand-edit casually.",
            where="Backend config (org standard); not committed secrets.",
            when="Any shared Terraform workspace.",
            who="Infra team.",
            why="Without state, Terraform cannot manage updates safely.",
            sources=[_s("Terraform state", "https://developer.hashicorp.com/terraform/language/state", "docs")],
            related_module_ids=["16-iac-terraform"],
        ),
        # FinOps
        FlashCard(
            id="fc-daily-budget",
            front="DailyCostBudget (LLM)",
            track="finops",
            tags=["finops", "budget"],
            kind="code",
            what="Circuit breaker that stops LLM spend after a daily USD ceiling.",
            how="finops/budget.py; settings.llm_cost_budget_usd_per_day; Redis-shared optional.",
            where="Gateway path when LLM calls happen.",
            when="Always when llm_enabled.",
            who="Platform FinOps.",
            why="Unbounded tokens = unbounded invoices.",
            code="if not budget.allow(est): raise BudgetExceeded\n# after call: budget.record(actual)",
            language="python",
            sources=[
                _s("FinOps Foundation", "https://www.finops.org/", "standard"),
                _s("Project finops/budget.py", "", "docs"),
            ],
            related_module_ids=["17-finops-cost"],
        ),
        FlashCard(
            id="fc-token-cost",
            front="Token cost formula",
            track="finops",
            tags=["finops", "llm"],
            kind="theory",
            what="Cost estimate for a completion from token counts and $/1M prices.",
            how="(in_tokens*price_in + out_tokens*price_out)/1e6",
            where="Pre-call estimates and post-call accounting.",
            when="Every billable model call.",
            who="FinOps + gateway.",
            why="Unit economics for AI features.",
            code="usd = (in_tok * p_in + out_tok * p_out) / 1_000_000",
            language="python",
            sources=[_s("Provider pricing pages (OpenAI/Anthropic/etc.)", "", "docs")],
            related_module_ids=["17-finops-cost"],
            difficulty="easy",
        ),
        FlashCard(
            id="fc-infra-cost-worksheet",
            front="Infra cost worksheet",
            track="finops",
            tags=["finops", "infra", "estimate"],
            kind="process",
            what="Structured inventory×price estimate for a stack.",
            how="List API, Neo4j, Redis, LB, obs, egress; price; divide by diagnoses/month.",
            where="Architecture reviews / capacity planning.",
            when="Before production scale commitments.",
            who="Architects + FinOps.",
            why="Avoid surprise cloud bills.",
            sources=[
                _s("Infracost", "https://www.infracost.io/", "docs"),
                _s("AWS Pricing Calculator (example)", "https://calculator.aws/", "docs"),
            ],
            related_module_ids=["17-finops-cost", "16-iac-terraform"],
        ),
        # Security
        FlashCard(
            id="fc-owasp-llm",
            front="OWASP LLM Top 10",
            track="security",
            tags=["owasp", "llm", "security"],
            kind="theory",
            what="Catalog of LLM application risks (injection, data leak, supply chain, etc.).",
            how="Map each risk to a control in security/owasp-llm-mapping.md + guardrails/evals.",
            where="security/",
            when="Threat modeling LLM features.",
            who="Security + app owners.",
            why="Shared language for LLM threats.",
            sources=[
                _s(
                    "OWASP Top 10 for LLM Applications",
                    "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
                    "standard",
                ),
            ],
            related_module_ids=["18-security-guardrails"],
        ),
        FlashCard(
            id="fc-guardrails-pipeline",
            front="Guardrails pipeline",
            track="security",
            tags=["guardrails", "security"],
            kind="process",
            what="Layered checks: rate → input → core → output → action.",
            how="guardrails/* wired in API middleware/pipeline.",
            where="guardrails/, api/main.py",
            when="Every request on protected paths.",
            who="API platform.",
            why="Defense in depth.",
            sources=[_s("Project guardrails/", "", "docs")],
            related_module_ids=["18-security-guardrails"],
        ),
        FlashCard(
            id="fc-pii-redaction",
            front="PII redaction in telemetry",
            track="security",
            tags=["pii", "privacy", "logs"],
            kind="pattern",
            what="Strip/mask personal data before logs/metrics export.",
            how="observability redaction when enable_pii_redaction=true.",
            where="observability/redaction.py",
            when="Always in production logging.",
            who="Security + platform.",
            why="Logs are a common leak channel.",
            sources=[
                _s("NIST Privacy Framework (overview)", "https://www.nist.gov/privacy-framework", "standard"),
            ],
            related_module_ids=["18-security-guardrails", "11-observability-monitoring"],
        ),
        # Integrations
        FlashCard(
            id="fc-anti-corruption",
            front="Anti-corruption layer (integrations)",
            track="integrations",
            tags=["ddd", "integrations"],
            kind="pattern",
            what="Translate external SoR models into the domain without polluting it.",
            how="integrations/* adapters; OntologyBuilder for knowledge.",
            where="integrations/, enterprise_pipeline transformers.",
            when="Connecting CRM/claims/PIM.",
            who="Integration engineers.",
            why="External schemas change; domain must stay stable.",
            sources=[
                _s("Evans — Domain-Driven Design (anti-corruption layer)", "", "book"),
            ],
            related_module_ids=["19-integrations", "03-etl-pipeline"],
        ),
        FlashCard(
            id="fc-mock-sor",
            front="Mock systems of record",
            track="integrations",
            tags=["mocks", "demo"],
            kind="pattern",
            what="Local fake enterprise apps for demos without prod credentials.",
            how="simulation/mock_enterprise_apps.py + fixtures under data/enterprise_sources/",
            where="simulation/, data/enterprise_sources/",
            when="Local/demo/CI without live SAP/SFDC.",
            who="Developers.",
            why="Unblock development; still validate adapter contracts.",
            sources=[_s("Project simulation/", "", "docs")],
            related_module_ids=["19-integrations"],
            difficulty="easy",
        ),
        # MLOps / AIOps / synthetic / images
        FlashCard(
            id="fc-mlops-loop",
            front="MLOps lifecycle loop",
            track="mlops",
            tags=["mlops", "lifecycle"],
            kind="process",
            what="Data→train→eval→registry→deploy→monitor→retrain/rollback.",
            how="Map to registry.yaml, evals/, gateway/, finops/ in this repo.",
            where="models/, evals/, gateway/",
            when="Any model-backed feature.",
            who="ML/platform engineers.",
            why="Models drift; lifecycle must be gated.",
            sources=[
                _s("Google MLOps whitepaper", "https://cloud.google.com/resources/mlops-whitepaper", "docs"),
            ],
            related_module_ids=["20-synthetic-mlops-images", "10-llmops-disciplines"],
        ),
        FlashCard(
            id="fc-synthetic-data",
            front="Synthetic diagnostic catalog data",
            track="mlops",
            tags=["synthetic-data", "privacy"],
            kind="pattern",
            what="Generated demo knowledge (products/symptoms/FMs) without real customer PII.",
            how="graph/synthetic_data_generator.py → catalog JSON; label simulated provenance.",
            where="graph/synthetic_data_generator.py, data/*synthetic*",
            when="Demos, tests, bootstrapping graphs.",
            who="Knowledge engineers.",
            why="Safe demos; still not a substitute for validated field knowledge.",
            sources=[
                _s("Project graph/synthetic_data_generator.py", "", "docs"),
            ],
            related_module_ids=["20-synthetic-mlops-images"],
        ),
        FlashCard(
            id="fc-diffusion-images",
            front="Diffusion image generation (concept)",
            track="mlops",
            tags=["images", "diffusion", "genai"],
            kind="theory",
            what="Generative method that denoises noise into images conditioned on prompts.",
            how="Train/infer diffusion models; ops need safety filters, rate limits, cost/image, retention.",
            where="Not core GraphRAG path; relevant if product adds multimodal features.",
            when="Designing image features.",
            who="GenAI engineers + platform security/finops.",
            why="Images change cost, abuse, and content-risk profile.",
            sources=[
                _s("Ho et al., DDPM", "https://arxiv.org/abs/2006.11239", "paper"),
            ],
            related_module_ids=["20-synthetic-mlops-images", "17-finops-cost"],
            difficulty="hard",
        ),
        FlashCard(
            id="fc-aiops",
            front="AIOps",
            track="aiops",
            tags=["aiops", "ops", "ml"],
            kind="concept",
            what="Using analytics/ML on ops telemetry to detect, correlate, and sometimes remediate incidents.",
            how="Start with Prometheus rules + runbooks; add anomaly models when data volume justifies.",
            where="monitoring/alerts + future detectors on metrics/logs.",
            when="After basic observability is trustworthy.",
            who="SRE/AIOps teams.",
            why="Reduce MTTR; avoid alert fatigue.",
            sources=[
                _s("Gartner AIOps (concept overview — vendor-neutral intro via industry defs)", "", "docs"),
                _s(
                    "Google SRE Book — practical alerting",
                    "https://sre.google/sre-book/monitoring-distributed-systems/",
                    "docs",
                ),
            ],
            related_module_ids=["20-synthetic-mlops-images", "11-observability-monitoring"],
        ),
        FlashCard(
            id="fc-finetune-gate",
            front="Fine-tune promotion gate",
            track="mlops",
            tags=["finetune", "evals"],
            kind="pattern",
            what="Do not ship a fine-tune without baseline eval comparison.",
            how="Train → eval vs baseline → record eval_baseline → pin registry alias.",
            where="models/finetunes/ README + evals/",
            when="Domain adaptation projects.",
            who="ML engineers.",
            why="Fine-tunes can regress safety or accuracy silently.",
            sources=[_s("Project models/finetunes/README.md", "", "docs")],
            related_module_ids=["20-synthetic-mlops-images", "12-evalops-gates"],
        ),
    ]
