apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: diagnostics-staging

resources:
  - ../../base

images:
  - name: ghcr.io/OWNER/REPO-diagnostics-api
    newTag: latest
  - name: ghcr.io/OWNER/REPO-diagnostics-ui
    newTag: latest
  - name: ghcr.io/OWNER/REPO-diagnostics-mock
    newTag: latest
  - name: ghcr.io/OWNER/REPO-diagnostics-etl
    newTag: latest